# Generated by Django 3.0 on 2021-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsrReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('pass_word', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
    ]
