# Generated by Django 3.0 on 2021-02-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrreg',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
